"""Parse the archived Publications page into a structured TS data file.

Reads:  /Users/oz/Developer/Claude Code/olivercrocco-archive/pages-markdown/suggested-reading_42.md
Writes: src/data/publications.ts
"""

import re
import json
from pathlib import Path

ARCHIVE = Path("/Users/oz/Developer/Claude Code/olivercrocco-archive")
SITE = Path("/Users/oz/Developer/Claude Code/olivercrocco-site")

src_md = (ARCHIVE / "pages-markdown" / "suggested-reading_42.md").read_text()


def clean(s):
    s = s.strip()
    s = re.sub(r"\s+", " ", s)
    return s


def parse_citation(line):
    """Return (citation_text, doi_url, venue_hint) from one bibliography line.

    Lines look like:
      Author A., & Author B. (2024). Title. *Journal*, 25(1), 1–20. [https://doi.org/...](https://doi.org/...)
    """
    line = clean(line)

    # Pull URL out of last [text](url) — typically the DOI
    url_match = re.search(r"\[([^\]]+)\]\(([^)]+)\)\s*\.?\s*$", line)
    url = ""
    if url_match:
        url = url_match.group(2).strip()
        # Strip the [text](url) from the citation
        line = line[: url_match.start()].rstrip()

    # Strip a trailing standalone https:// URL if any
    line = re.sub(r"\s+https?://\S+\s*\.?\s*$", "", line)

    # Convert remaining markdown italics to plain text but preserve the journal name in the data.
    # We'll keep markdown italic markers in the citation text, since the page renderer uses them.
    citation = clean(line).rstrip(".") + "."

    return citation, url


def derive_venue(citation):
    """Pull the journal/book name from a markdown-italic span in the citation."""
    m = re.search(r"\*([^*]+)\*", citation)
    return m.group(1).strip().rstrip(",") if m else ""


def derive_year(citation):
    m = re.search(r"\((\d{4})", citation)
    return int(m.group(1)) if m else None


# ---- Walk the page ----
publications = []  # list of dicts
current_section = None

# Split by lines and process headings
for raw in src_md.splitlines():
    raw = raw.rstrip()
    if not raw:
        continue
    # Headings (single # is the page title; ## is "In Press"; # used inconsistently as year markers)
    h = re.match(r"^#+\s+(.+)$", raw)
    if h:
        head = h.group(1).strip()
        if head.lower() == "publications":
            continue
        # "In Press", "2026", "2025", "Pre-2019"
        current_section = head
        continue
    # Citation lines
    if raw.startswith("---"):
        continue
    citation, url = parse_citation(raw)
    if len(citation) < 30:
        # skip noise (headings parsed as text, etc.)
        continue
    venue = derive_venue(citation)
    year = derive_year(citation)
    publications.append({
        "section": current_section or "Other",
        "year": year,
        "citation": citation,
        "venue": venue,
        "url": url,
    })

# Stable order: by section as encountered, then year desc within
sections_order = []
for p in publications:
    if p["section"] not in sections_order:
        sections_order.append(p["section"])

# Group
grouped = {s: [] for s in sections_order}
for p in publications:
    grouped[p["section"]].append(p)

# ---- Write TS file ----
ts_lines = [
    "/**",
    " * Auto-generated by scripts/extract_publications.py from the archived",
    " * WordPress Publications page. Edit the source if you need changes.",
    " */",
    "",
    "export interface Publication {",
    "  section: string;",
    "  year: number | null;",
    "  citation: string;",
    "  venue: string;",
    "  url: string;",
    "}",
    "",
    "export const PUBLICATIONS: Publication[] = [",
]

for section in sections_order:
    ts_lines.append(f"  // === {section} ===")
    for p in grouped[section]:
        ts_lines.append(
            "  {"
            f"section: {json.dumps(p['section'])}, "
            f"year: {p['year'] if p['year'] is not None else 'null'}, "
            f"citation: {json.dumps(p['citation'])}, "
            f"venue: {json.dumps(p['venue'])}, "
            f"url: {json.dumps(p['url'])}"
            "},"
        )

ts_lines.append("];")
ts_lines.append("")
ts_lines.append("export const PUBLICATION_SECTIONS: string[] = " + json.dumps(sections_order) + ";")
ts_lines.append("")

(SITE / "src" / "data" / "publications.ts").write_text("\n".join(ts_lines))
print(f"✓ Wrote {len(publications)} publications across {len(sections_order)} sections")
print(f"  Sections: {sections_order}")
